modLoader="javafml"

loaderVersion="[28,)"

license="All rights reserved"

[[mods]]

modId="xlife"

version="1.15.2-1.0"

displayName="X Life"

authors="jayhill❤"

description='''
Recreation of the X Life YouTube SMP mod!
'''