modLoader="javafml"

loaderVersion="[28,)"

[[mods]]

modId="xlife"

version="1.14.2-1.0"

displayName="X Life"

credits="pau101"

authors="jay❤"

description='''
Start with one heart and ten lives, everytime you die, you gain one heart and lose a life.
'''